server:
  port: 9101

dubbo:
  application:
    name: springboot-dubbo-consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 28092
  monitor:
    protocol: registry